namespace WSL;

public static partial class WslApiLoader {
    [Flags]
    public enum WSL_DISTRIBUTION_FLAGS {
        WSL_DISTRIBUTION_FLAGS_NONE = 0x0,
        WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP = 0x1,
        WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH = 0x2,
        WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING = 0x4
    }

    public static WSL_DISTRIBUTION_FLAGS WSL_DISTRIBUTION_FLAGS_VALID =
        WSL_DISTRIBUTION_FLAGS.WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP |
        WSL_DISTRIBUTION_FLAGS.WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH |
        WSL_DISTRIBUTION_FLAGS.WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING;

    public static WSL_DISTRIBUTION_FLAGS WSL_DISTRIBUTION_FLAGS_DEFAULT =
        WSL_DISTRIBUTION_FLAGS.WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP |
        WSL_DISTRIBUTION_FLAGS.WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH |
        WSL_DISTRIBUTION_FLAGS.WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING;
}
