runs:
  using: 'composite'
  steps:
    - name: Check for nix ✅
      id: check-nix
      shell: bash
      run: |
        if command -v nix &> /dev/null
        then
          echo "nix-found=true" | tee -a $GITHUB_OUTPUT
        else
          echo "nix-found=false" | tee -a $GITHUB_OUTPUT
        fi

    - name: Install Nix ❄️
      if: ${{ steps.check-nix.outputs.nix-found != 'true' }}
      uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
      with:
        github_access_token: ${{ github.token }}
