[package]
name = "nixos-wsl-native-systemd-shim"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "*", features = ["backtrace"] }
nix = { version = "*", features = ["process"] }
log = "*"
kernlog = "*"