outputs:
  version:
    description: 'The generated version number'
    value: ${{ steps.version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Generate Version 🏷️
      id: version
      shell: pwsh
      run: |
        if ('${{ github.event_name }}' -eq 'pull_request') {
          $version = 'pr-${{ github.event.pull_request.number }}'
          $is_numeric = ''
        } elseif ('${{ github.ref_name }}' -like 'release-*') {
          $latest_tag = git describe --tags --abbrev=0
          $commit_count = git rev-list --use-bitmap-index --count "$(git rev-list --tags --no-walk --max-count=1)..HEAD"
          $version = "$($latest_tag -replace '(.+)\.(.+)\.(.+)\..+', '$1.$2.$3').${commit_count}"
          $is_numeric = 1
        } else {
          $version = '${{ github.ref_name }}'
          $is_numeric = ''
        }
        "version=$version" | Tee-Object -FilePath $env:GITHUB_OUTPUT -Append
        "is_numeric=$is_numeric" | Tee-Object -FilePath $env:GITHUB_OUTPUT -Append

    - name: Set Version 🏷️
      shell: pwsh
      run: |
        Write-Output '${{ steps.version.outputs.version }}' | Tee-Object -FilePath ./VERSION
        Write-Output "$(git rev-parse HEAD)" | Tee-Object -FilePath ./VERSION -Append

    - name: Set Launcher Version 🏷️
      shell: pwsh
      if: ${{ steps.version.outputs.is_numeric }}
      run: |
        ((Get-Content -path ./Launcher/Launcher/Launcher.csproj -Raw) -replace '1.3.3.7','${{ steps.version.outputs.version }}') | Set-Content -Path ./Launcher/Launcher/Launcher.csproj
        ((Get-Content -path ./Launcher/Launcher-Appx/Package.appxmanifest -Raw) -replace '1.3.3.7','${{ steps.version.outputs.version }}') | Set-Content -Path ./Launcher/Launcher-Appx/Package.appxmanifest
