outputs:
  dotnet-version:
    value: ${{ steps.setup-dotnet.outputs.dotnet-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup MSBuild # Needed for APPX packaging
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
      with:
        vs-version: '[17.2,'

    - name: Setup .NET SDK
      id: setup-dotnet
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: 8
        cache: true
        cache-dependency-path: 'Launcher/Launcher/packages.lock.json'

    - name: Run NuGet restore
      shell: pwsh
      working-directory: 'Launcher'
      run: nuget restore
