name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build 🛠️
    uses: ./.github/workflows/run_build.yml

  release:
    needs:
      - build
    name: Create Release 📢
    runs-on: ubuntu-latest
    steps:
      - name: Download Tarball 📥
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: tarball

      - name: Generate Checksums 🔑
        run: |
          sha256sum nixos.wsl > nixos.wsl.sha256

      - name: Attach to Release 📎
        uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7 # v2.3.4
        with:
          files: |
            nixos.wsl
            nixos.wsl.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
