name: "Release"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build 🛠️
    uses: ./.github/workflows/run_build.yml

  release:
    needs:
      - build
    name: Create Release 📢
    runs-on: ubuntu-24.04
    steps:
      - name: Download x86_64 Tarball 📥
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: tarball-x86_64

      - name: Download aarch64 Tarball 📥
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: tarball-aarch64

      - name: Generate Checksums 🔑
        run: |
          sha256sum nixos.wsl > nixos.wsl.sha256
          sha256sum nixos.aarch64.wsl > nixos.aarch64.wsl.sha256

      - name: Attach to Release 📎
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          files: |
            nixos.wsl
            nixos.wsl.sha256
            nixos.aarch64.wsl
            nixos.aarch64.wsl.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
