name: Build Tarball

on:
  workflow_call: {}

jobs:
  tar:
    name: Tarball (${{ matrix.system }}) 🛠️
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            system: x86_64
            config: default
            filename: nixos.wsl
          - runner: ubuntu-24.04-arm
            system: aarch64
            config: aarch64
            filename: nixos.aarch64.wsl
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Set Version 🏷️
        uses: ./.github/actions/version
        id: version

      - name: Summary Headline 📝
        run: echo '## NixOS-WSL ${{ steps.version.outputs.version }}' >> $GITHUB_STEP_SUMMARY

      - name: Build Tarball 🛠️
        uses: ./.github/actions/build-wsl-tarball
        with:
          config: ${{ matrix.config }}
          filename: ${{ matrix.filename }}

      - name: Upload Tarball 📤
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: tarball-${{ matrix.system }}
          path: ${{ matrix.filename }}
