name: Documentation

on:
  workflow_call: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "${{ github.ref == 'refs/heads/main' && 'docs' || github.run_id }}"
  cancel-in-progress: false

jobs:
  prepare:
    name: Documentation 📕
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Build documentation 🛠️
        id: build
        uses: ./.github/actions/build-nix-expression
        with:
          expression: ".#docs"

      - name: Patch 404.html 🩹
        run: |
          cp -r ${{ steps.build.outputs.derivation }}/. dist
          chmod -R +w dist
          sed -i 's|<base href="/">|<base href="/NixOS-WSL">|' dist/404.html

      - name: Upload documentation 📥
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: dist

      - name: Deploy to GitHub Pages 🚀
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
