name: Tests

on:
  workflow_call: {}

jobs:
  prepare:
    name: Find Tests 🔍
    runs-on: ubuntu-24.04
    outputs:
      tests: ${{ steps.tests.outputs.tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Find Tests 🔍
        id: tests
        run: |
          find tests -name '*.Tests.ps1' -print0 | perl -pe 's|(.*?)\x0|"\1",|g;s|,$||;s|(.*)|tests=[\1]|' >> $GITHUB_OUTPUT

  # Note: Tests only run on x86_64. The windows-11-arm runner does not support nested virtualization.
  tests:
    name: Test 🧪
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.prepare.outputs.tests) }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Download Tarball 📥
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: tarball-x86_64

      - name: Setup WSL 🐧
        run: |
          wsl --update
          Get-Command wsl
          wsl --version

      - name: Execute Test 🧪
        shell: pwsh
        run: Invoke-Pester -Output Detailed ${{ matrix.test }}
