name: Build Tarball

on:
  workflow_call: {}

jobs:
  tar:
    name: Tarball 🛠️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix ❄️
        uses: ./.github/actions/install-nix

      - name: Set Version 🏷️
        uses: ./.github/actions/version
        id: version

      - name: Summary Headline 📝
        run: echo '## NixOS-WSL ${{ steps.version.outputs.version }}' >> $GITHUB_STEP_SUMMARY

      - name: Build Tarball 🛠️
        uses: ./.github/actions/build-wsl-tarball
        with:
          config: default
          filename: nixos.wsl

      - name: Upload Tarball 📤
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: tarball
          path: nixos.wsl
