name: "NixOS Config Tests"

on:
  pull_request:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.rst'
      - '.gitignore'

jobs:
  NixOS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.11

      - name: "Test NixOS Configuration ❄️"
        run: nix-build -E "(import <nixpkgs> {}).nixos ./configuration.nix"
